version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:ai-beta
    restart: always
    ports:
      - "0.0.0.0:5678:5678"
    environment:
      - N8N_HOST=n8n.zaplaunch.com.br
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.zaplaunch.com.br/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data1:/home/node/.n8n

volumes:
  n8n_data:
    external: true
